name: Deploy Ghost CMS to AWS

on:
  push:
    branches:
      - main


jobs:
  semgrep_scan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Semgrep
        run: pip install semgrep

      - name: Run Semgrep scan on Terraform
        id: semgrep
        run: semgrep --config=p/terraform .

      - name: Notify Slack if Semgrep finds issues
        if: failure()
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"⚠️ *Semgrep* found security issues in the Terraform code. Please check the GitHub Actions logs for details."}' $SLACK_WEBHOOK_URL

  deploy:
    needs: semgrep_scan
    if: success() && needs.semgrep_scan.result == 'success'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
  terraform:
    name: Deploy to AWS with Terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Plan
        working-directory: ./terraform
        run: terraform plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
